bandcamp_page: "plzmakeitruins"
embed_code: "<iframe style='border: 0; width: 500px; height: 796px;' src='https://bandcamp.com/EmbeddedPlayer/album=/size=large/bgcol=ffffff/linkcol=0687f5/package=967020329/transparent=true/'' seamless''></iframe>"
youtube_channel: "UCsU0dihadDYCeXXIqUMEr3Q"
